# Auto-generated launcher for EbookAutomation scheduled task
# Regenerated by Install-EbookScheduledTask -- do not edit manually
$ErrorActionPreference = 'Continue'

try {
    Import-Module 'F:\Projects\EbookAutomation\module\EbookAutomation.psm1' -Force

    # Read user defaults for pipeline flags
    $defaults = Get-EbookDefaults

    $pipelineArgs = @{}
    if ($defaults.generate_mp3)       { $pipelineArgs['GenerateMP3'] = $true }
    if ($defaults.use_claude_chapters) { $pipelineArgs['UseClaudeChapters'] = $true }

    Invoke-EbookPipeline @pipelineArgs
}
catch {
    # Write error to a persistent location (not just console)
    $errorLog = Join-Path 'F:\Projects\EbookAutomation' 'logs' 'scheduler-errors.txt'
    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    "$timestamp  SCHEDULER ERROR: $_" | Add-Content $errorLog -Encoding UTF8
    "$timestamp  Stack: $($_.ScriptStackTrace)" | Add-Content $errorLog -Encoding UTF8
    exit 1
}
